package com.campus.platform.push

import android.util.Log
import io.github.jan.supabase.SupabaseClient
import io.github.jan.supabase.postgrest.postgrest
import kotlinx.coroutines.CancellationException
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.time.Instant
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Manages the FCM device token lifecycle with the Supabase fcm_tokens table.
 *
 * Token flow:
 *   1. Firebase SDK generates/refreshes token → onNewToken()
 *   2. FcmTokenManager.saveToken() upserts to fcm_tokens
 *   3. On logout → deactivateAllTokens() sets is_active=false
 *   4. On token refresh → old token deactivated, new token saved
 *
 * The fcm_tokens table has a UNIQUE(token) constraint, so upsert by
 * deleting any existing row with the same token value then inserting.
 */
@Singleton
class FcmTokenManager @Inject constructor(
    private val supabase: SupabaseClient,
) {

    companion object {
        private const val TAG = "FcmTokenManager"
    }

    // ── DTO ────────────────────────────────────────────────────

    @Serializable
    data class FcmTokenDto(
        val id: String? = null, // generated by DB
        @SerialName("user_id") val userId: String,
        val token: String,
        val platform: String = "android",
        @SerialName("device_name") val deviceName: String? = null,
        @SerialName("is_active") val isActive: Boolean = true,
        @SerialName("last_used_at") val lastUsedAt: String? = null,
    )

    // ── Public API ─────────────────────────────────────────────

    /**
     * Save or reactivate a token for the current user.
     *
     * If a row with this token already exists (e.g. from a previous session),
     * it is updated. Otherwise a new row is inserted.
     */
    suspend fun saveToken(userId: String, token: String, deviceName: String? = null) {
        try {
            val now = Instant.now().toString()

            // Check if this token already exists for this user
            val existing = supabase.postgrest
                .from("fcm_tokens")
                .select { filter { eq("token", token) } }
                .decodeList<FcmTokenDto>()

            if (existing.isNotEmpty()) {
                // Reactivate existing token
                supabase.postgrest
                    .from("fcm_tokens")
                    .update(mapOf(
                        "user_id" to userId,
                        "is_active" to true,
                        "device_name" to (deviceName ?: existing.first().deviceName),
                        "last_used_at" to now,
                        "updated_at" to now,
                    )) {
                        filter { eq("token", token) }
                    }
            } else {
                // Insert new token
                supabase.postgrest
                    .from("fcm_tokens")
                    .insert(FcmTokenDto(
                        userId = userId,
                        token = token,
                        platform = "android",
                        deviceName = deviceName,
                        isActive = true,
                        lastUsedAt = now,
                    ))
            }

            Log.i(TAG, "Token saved for user $userId")
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Log.e(TAG, "Failed to save FCM token", e)
        }
    }

    /**
     * Deactivate a specific token (e.g. on token refresh, old token is retired).
     */
    suspend fun deactivateToken(token: String) {
        try {
            val now = Instant.now().toString()
            supabase.postgrest
                .from("fcm_tokens")
                .update(mapOf(
                    "is_active" to false,
                    "updated_at" to now,
                )) {
                    filter { eq("token", token) }
                }
            Log.i(TAG, "Token deactivated")
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Log.e(TAG, "Failed to deactivate token", e)
        }
    }

    /**
     * Deactivate all tokens for a user (called on logout).
     * The records are preserved for auditing; FCM will reject messages
     * for invalidated tokens on the EdgeFn side.
     */
    suspend fun deactivateAllTokens(userId: String) {
        try {
            val now = Instant.now().toString()
            supabase.postgrest
                .from("fcm_tokens")
                .update(mapOf(
                    "is_active" to false,
                    "updated_at" to now,
                )) {
                    filter {
                        eq("user_id", userId)
                        eq("is_active", true)
                    }
                }
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Log.e(TAG, "Failed to deactivate all tokens", e)
        }
    }

    /**
     * Delete a specific token entirely (e.g. user explicitly removes a device).
     */
    suspend fun deleteToken(token: String) {
        try {
            supabase.postgrest
                .from("fcm_tokens")
                .delete { filter { eq("token", token) } }
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Log.e(TAG, "Failed to delete token", e)
        }
    }
}
